buildscript {
    // KITA HAPUS 'ext.kotlin_version' DARI SINI

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // Versi ini harus cocok dengan 'settings.gradle' Anda
        classpath 'com.android.tools.build:gradle:8.6.0'

        // --- INI PERBAIKANNYA ---
        // KITA HAPUS BARIS INI:
        // classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // (Ini sudah diatur oleh settings.gradle)
        // --- AKHIR PERBAIKAN ---

        // Versi ini harus cocok dengan 'settings.gradle' Anda
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

