// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFM024Q8A5-f7ZjFq8IuDC07eW-7_lXTs',
    appId: '1:1048599871385:web:8708411faf44814686dd08',
    messagingSenderId: '1048599871385',
    projectId: 'mbois-fcf62',
    authDomain: 'mbois-fcf62.firebaseapp.com',
    storageBucket: 'mbois-fcf62.firebasestorage.app',
    measurementId: 'G-YDZG9X11ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdNA9zX8vbBFR0G0oueoi32-kiLSx-bZE',
    appId: '1:1048599871385:android:8cf48f0a4e6c7a8486dd08',
    messagingSenderId: '1048599871385',
    projectId: 'mbois-fcf62',
    storageBucket: 'mbois-fcf62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3SPhAOgou7oS3UOTwltkgOlEgIwmPwKg',
    appId: '1:1048599871385:ios:a2a17db4d38ba1dd86dd08',
    messagingSenderId: '1048599871385',
    projectId: 'mbois-fcf62',
    storageBucket: 'mbois-fcf62.firebasestorage.app',
    iosBundleId: 'com.bps.mboistats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3SPhAOgou7oS3UOTwltkgOlEgIwmPwKg',
    appId: '1:1048599871385:ios:a2a17db4d38ba1dd86dd08',
    messagingSenderId: '1048599871385',
    projectId: 'mbois-fcf62',
    storageBucket: 'mbois-fcf62.firebasestorage.app',
    iosBundleId: 'com.bps.mboistats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFM024Q8A5-f7ZjFq8IuDC07eW-7_lXTs',
    appId: '1:1048599871385:web:b308373fb2c825d586dd08',
    messagingSenderId: '1048599871385',
    projectId: 'mbois-fcf62',
    authDomain: 'mbois-fcf62.firebaseapp.com',
    storageBucket: 'mbois-fcf62.firebasestorage.app',
    measurementId: 'G-BX0GL6GD70',
  );
}
